### ISSUE TITLE
Not compatible with QGIS 3

### ISSUE THREAD

**Issue by st3255** [erpas/rgis#32]
Is this project being ported to QGIS3? Is or will there be any active development, or is this project dead?
(the re-import of Hec-Ras results would be very useful and would make this a real complete solution!)

**Comment by erpas** [comment]
Hi st3255,

Thanks for your interest in RiverGIS!
Yes, we are considering porting the plugin to QGIS3 and switching to Geopackage as a data storage instead of PostGIS. It very much depends on collecting some funds, as we are now involved in other projects and having very limited free time. Please, let us if you would like to participate.

Regarding loading HEC-RAS results back into QGIS, please use Crayfish plugin [2]. Currently it reads 2D cases. 


[1] https://www.linkedin.com/groups/1908568/1908568-6383341019278245892
[2] https://www.lutraconsulting.co.uk/products/crayfish/

**Comment by st3255** [comment]
Thank you for your work. I will see if we are able to support you financially.

Regarding the re-import to QGIS: Also the import of 1D-Cases would be interesting / nice to have (kind of possible via exporting it from the viewer within HEC-Ras, but also not as easy as with GeoRAS!).

**Comment by erpas** [comment]
The plugin was ported to QGIS 3 and can be installed from QGIS Plugin Manager.
